---
title: "Metro"
author: "Yixuan (Sherry) Wu"
date: "December 5, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lubridate)
library(tidyverse)
library(lmtest)
library(tseries)
library(dplyr)
library(forecast)
library(TSA)
```

##Exploration

```{r}
Metro = read_csv("Metro_Interstate_Traffic_Volume.csv")
```

###Data Cleaning:

```{r}
MetroRemoved = Metro[duplicated(Metro$date_time) == F,]
MetroRemoved = MetroRemoved[year(MetroRemoved$date_time) <2015,]

###aggregate by date:

MetroRemoved$ho = MetroRemoved$holiday
MetroRemoved$ho[MetroRemoved$holiday == "None"] = 0
MetroRemoved$ho[MetroRemoved$holiday != "None"] = 1
MetroRemoved$ho = as.numeric(MetroRemoved$ho)


MetroNew = MetroRemoved %>%
  group_by(date(MetroRemoved$date_time)) %>%
  summarise(Volume = mean(traffic_volume),
            Rain = mean(rain_1h),
            Snow = mean(snow_1h),
            Cloud = mean(clouds_all),
            Temp = mean(temp),
            Holiday = if(mean(ho) > 0){1}else{0})

names(MetroNew)[1] = "Date"

###check if any day is missing:
DateRange = seq(min(MetroNew$Date), max(MetroNew$Date), by = 1)
MissingDate = DateRange[!DateRange %in% MetroNew$Date ]

MetroNew$Date = as.numeric(MetroNew$Date)

for (i in 1:length(MissingDate)) 
  {
    newrow = as.numeric(c(MissingDate[i], rep(NA, 6)))
    MetroNew = rbind(MetroNew, newrow)
  }

MetroNew$Date = as.Date(MetroNew$Date)
##Reorder the data by date
MetroNew = MetroNew %>% arrange(Date)

##Making Volume into a ts object by date
Metro.ts = ts(MetroNew$Volume, start = c(2012.75), frequency = 366)

#Remove TS object containing NAs lines

Metro.ts = na.remove(Metro.ts)

plot(Metro.ts)
# Metro.ts = zoo(MetroRemoved$traffic_volume,MetroRemoved$date_time)
# Metro.ts = as.ts(Metro.ts)
# Metro.ts = Metro.ts[!is.na(Metro.ts)]

# plot(Metro.ts)
# plot(MetroRemoved$date_time, MetroRemoved$traffic_volume)
```

###Conditions Check

```{r}
Metro.lm = lm(MetroNew$Volume ~ MetroNew$Date)

summary(Metro.lm)
plot(Metro.lm)
dwtest(Metro.lm)
```

Stationarity and Autocorrelation:

Seems to have no trend -- stationary, but seasonality from the ACF plot

```{r}
dwtest(Metro.ts)
acf(Metro.ts)
adf.test(Metro.ts)
```


```{r}
ggplot() +
  geom_line(aes(x = time(Metro.ts), y = Metro.ts), color = "#044bc4") +
  scale_y_continuous() +
  scale_x_continuous() +
  labs(y = "Metro Volume", x = element_blank(), title = "Time Series Plot of Metro Volume") +
  theme_minimal() +
  theme(axis.text = element_text(size = 14),
        text = element_text(size = 16))

```



###Smoothing

```{r}
ts.Kernel = ksmooth(time(Metro.ts), Metro.ts, "normal", bandwidth = 0.2)
ts.Lowess = lowess(Metro.ts, f= 0.15)
difftime = time(Metro.ts) - mean(time(Metro.ts))
ts.Cubic = lm(Metro.ts ~ difftime + (difftime)^2 + (difftime)^3)

expts = ts(MetroNew$Volume, start = c(2012, 10,2))
expts = na.remove(expts)

ggplot() +
  geom_line(aes(x = time(Metro.ts), y = Metro.ts), color = "#63666A") +
  geom_line(aes(x = ts.Kernel$x, y = ts.Kernel$y, color = "Kernel Smoothing"), size = 1.5) +
  geom_line(aes(x = ts.Lowess$x, y = ts.Lowess$y, color = "Lowess Smoothing"), size = 1.2) +
  geom_smooth(method = "lm", aes(x = time(Metro.ts), y = Metro.ts, color = "Cubic Smoothing"), formula = (y~x + x^2 + x^3), size = 1.2, se = F) + 
  labs(x = element_blank(), y = "Metro Volume", title = "Smoothing of Metro Volume") +
  scale_y_continuous() +
  scale_x_continuous() +
  scale_color_manual(values = c("#75A4B9", "#044bc4", "#c48104")) +
  theme_minimal() +
  theme(legend.title=element_blank(), legend.position = c(0.75,1), legend.text=element_text(size=14),
        axis.text = element_text(size = 14),
        text = element_text(size = 16))
```



##Model Fitting

###Arima

```{r}
arima100 = arima(Metro.ts, order = c(1,0,0))
arima001 = arima(Metro.ts, order = c(0,0,1))
arima101 = arima(Metro.ts, order = c(1,0,1))
arima200 = arima(Metro.ts, order = c(2,0,0))
arima002 = arima(Metro.ts, order = c(0,0,2))
arima102 = arima(Metro.ts, order = c(1,0,2))
arima201 = arima(Metro.ts, order = c(2,0,1))
arima300 = arima(Metro.ts, order = c(3,0,0))
arima003 = arima(Metro.ts, order = c(0,0,3))
arima301 = arima(Metro.ts, order = c(3,0,1))
arima103 = arima(Metro.ts, order = c(1,0,3))
arima202 = arima(Metro.ts, order = c(2,0,2))

arima100
arima001
arima101
arima200
arima002
arima102
arima201
arima300
arima003
arima301
arima103
arima202

```

###Sarima

```{r}
sarima100 = arima(Metro.ts, order = c(2,0,2), seasonal = list(order = c(1,0,0), period = 7))
sarima001 = arima(Metro.ts, order = c(2,0,2), seasonal = list(order = c(0,0,1), period = 7))
sarima101 = arima(Metro.ts, order = c(2,0,2), seasonal = list(order = c(1,0,1), period = 7))
sarima200 = arima(Metro.ts, order = c(2,0,2), seasonal = list(order = c(2,0,0), period = 7))
sarima002 = arima(Metro.ts, order = c(2,0,2), seasonal = list(order = c(0,0,2), period = 7))
sarima201 = arima(Metro.ts, order = c(2,0,2), seasonal = list(order = c(2,0,1), period = 7))
sarima102 = arima(Metro.ts, order = c(2,0,2), seasonal = list(order = c(1,0,2), period = 7))
sarima202 = arima(Metro.ts, order = c(2,0,2), seasonal = list(order = c(2,0,2), period = 7))

sarima100
sarima001
sarima101
sarima200
sarima002
sarima201
sarima102
sarima202
```

Smallest AIC: 102, 201, 101.
Look at the ACF of them:

```{r}
acf(sarima100$residuals)
acf(sarima001$residuals)
acf(sarima101$residuals)
acf(sarima200$residuals)
acf(sarima002$residuals)
acf(sarima201$residuals)
acf(sarima102$residuals)
acf(sarima202$residuals)

```


```{r}
FinalModel = sarima101
Pred = predict(FinalModel, n.ahead = 365)
Pred.up = Pred$pred + 1.96 * Pred$se
Pred.lo = Pred$pred - 1.96 * Pred$se
```


##Forecasting:

```{r}
a = date(Metro$date_time)[date(Metro$date_time) >2014]

b = Metro$traffic_volume[date(Metro$date_time) >2014]

c = as.data.frame(cbind(a,b))

c = c %>% group_by(Date = date(Metro$date_time)) %>% summarise(Volume = mean(b))

ts.a = ts(c$Volume, start = c(2015.42), frequency = 365)

ggplot() +
  geom_line(aes(x = time(Metro.ts), y = Metro.ts)) +
  geom_line(aes(x = time(Pred$pred), y = as.matrix(Pred$pred)), color = "#044bc4") +
  geom_line(aes(x = time(Pred$pred), y = as.matrix(Pred.up)), color = "#75A4B9") +
  geom_line(aes(x = time(Pred$pred), y = as.matrix(Pred.lo)), color = "#75A4B9") +
  labs(x = element_blank(), y = "Metro Volume", title = "1 Yr Forecast with 95 Percent CI") +
  scale_x_continuous() +
  scale_y_continuous() +
  theme_minimal() +
  theme(axis.text = element_text(size = 14),
        text = element_text(size = 16))
```


```{r}

FinalModel2 = arima(window(Metro.ts, end = 2014.557), order = c(2,0,2), seasonal = list(order = c(1,0,1), period = 7))
Pred1 = predict(FinalModel2, n.ahead = 14)
Pred1.up = Pred1$pred + 1.96 * Pred1$se
Pred1.lo = Pred1$pred - 1.96 * Pred1$se


ggplot() +
  geom_line(aes(x = time(Metro.ts), y = Metro.ts)) +
  geom_line(aes(x = time(Pred1$pred), y = as.matrix(Pred1$pred)), color = "#044bc4", size = 1.2) +
  geom_line(aes(x = time(Pred1$pred), y = as.matrix(Pred1.up)), color = "#75A4B9", size = 1.2) +
  geom_line(aes(x = time(Pred1$pred), y = as.matrix(Pred1.lo)), color = "#75A4B9", size = 1.2) +
  labs(x = element_blank(), y = "Metro Volume", title = "2-Week Forecast with 95 Percent CI") +
  scale_x_continuous(limits = c(2014.5, 2014.6), breaks = c(2014.5, 2014.55, 2014.6)) +
  scale_y_continuous() +
  theme_minimal() +
  theme(axis.text = element_text(size = 14),
        text = element_text(size = 16))
```


##Regression


Exploratory Analysis:

```{r} 
ggplot(MetroNew, aes(x = MetroNew$Cloud)) +
  geom_histogram(bins = 20, fill = "#75A4B9", color = "black") +
  labs(x = "Cloud", y = "Counts", title = "Histogram of Cloud") +
  theme_minimal()+
  theme(text = element_text(size = 16),
        axis.text = element_text(size = 15))
```


```{r}
ggplot(MetroNew, aes(x = MetroNew$Temp)) +
  geom_histogram(bins = 20, fill = "#75A4B9", color = "black") +
  labs(x = "Temperatures", y = "Counts", title = "Histogram of Temperatures") +
  theme_minimal() +
  theme(text = element_text(size = 16),
        axis.text = element_text(size = 15))
```



```{r}
MetroNew1 = MetroNew[!is.na(MetroNew$Volume),]

tempreg = arima(Metro.ts, order = c(2,0,2), seasonal = list(order = c(1,0,1), period = 7), xreg = MetroNew1$Temp)

rainreg = arima(Metro.ts, order = c(2,0,2), seasonal = list(order = c(1,0,1), period = 7), xreg = MetroNew1$Rain )

cloudreg = arima(Metro.ts, order = c(2,0,2), seasonal = list(order = c(1,0,1), period = 7), xreg = MetroNew1$Cloud )

holidayreg = arima(Metro.ts, order = c(2,0,2), seasonal = list(order = c(1,0,1), period = 7), xreg = MetroNew1$Holiday)

PredictorMatrix = MetroNew1 %>% 
  select(Temp, Rain, Cloud, Holiday)

allreg = arima(Metro.ts, order = c(2,0,2), seasonal = list(order = c(1,0,1), period = 7), xreg = PredictorMatrix)


summary(tempreg)
summary(rainreg)
summary(cloudreg)
summary(holidayreg)

summary(allreg)
```


$$\begin{align}
\hat{Z_t} & = 1.019 Z_{t-1} -0.8638 Z_{t-2} - 0.8765 w_{t-1} +0.7703 w_{t-2} \\
 &+0.9499 Z_{t-7} -0.7544 w_{t-7} + 1309.1347\\
 & + 7.2045 x_1 -127.6794 x_2 - 0.2651 x_3 - 924.1027 x_4 \\
\end{align}$$
where $x_1$ is Temperature, $x_2$ is Rain, $x_3$ is Cloud, $x_4$ is Holiday

##Test set

```{r}
MetroTest = Metro[duplicated(Metro$date_time) == F,]
MetroTest = MetroTest[year(MetroTest$date_time) >2014,]

MetroTest$ho = MetroTest$holiday
MetroTest$ho[MetroTest$holiday == "None"] = 0
MetroTest$ho[MetroTest$holiday != "None"] = 1
MetroTest$ho = as.numeric(MetroTest$ho)


MetroNewTest = MetroTest %>%
  group_by(date(MetroTest$date_time)) %>%
  summarise(Volume = mean(traffic_volume),
            Rain = mean(rain_1h),
            Snow = mean(snow_1h),
            Cloud = mean(clouds_all),
            Temp = mean(temp),
            Holiday = if(mean(ho) > 0){1}else{0})

names(MetroNewTest)[1] = "Date"

###check if any day is missing:
DateRangeTest = seq(min(MetroNewTest$Date), max(MetroNewTest$Date), by = 1)
MissingDateTest = DateRangeTest[!DateRangeTest %in% MetroNewTest$Date]

MetroNewTest$Date = as.numeric(MetroNewTest$Date)

for (i in 1:length(MissingDateTest)) 
  {
    newrow = as.numeric(c(MissingDateTest[i], rep(NA, 6)))
    MetroNewTest = rbind(MetroNewTest, newrow)
  }

MetroNewTest$Date = as.Date(MetroNewTest$Date)
##Reorder the data by date
MetroNewTest = MetroNewTest %>% arrange(Date)
```


```{r}
Metro.ts1 = ts(MetroNewTest$Volume, start = c(2015.44), frequency = 365)
Metro.ts1 = na.remove(Metro.ts1)

ggplot() +
  geom_line(aes(x = time(Metro.ts1), y = Metro.ts1), color = "#044bc4") +
  scale_y_continuous() +
  scale_x_continuous() +
  labs(y = "Metro Volume", x = element_blank(), title = "Time Series Plot of Metro Volume Test") +
  theme_minimal() +
  theme(axis.text = element_text(size = 14),
        text = element_text(size = 16))

```

```{r}

acf(Metro.ts1)



testmodel = arima(Metro.ts1, order = c(2,0,2), seasonal = list(order = c(1,0,1), period = 7))

acf(testmodel$residuals)
```

```{r}
narima212 = arima(Metro.ts1, order = c(2,1,2), seasonal = list(order = c(1,0,1), period = 7))
narima202 = arima(Metro.ts1, order = c(2,0,2), seasonal = list(order = c(1,0,2), period = 7))
acf(narima202$residuals)

narima503 = arima(Metro.ts1, order = c(5,0,3), seasonal = list(order = c(1,0,1), period = 7))
narima513 = arima(Metro.ts1, order = c(5,1,3), seasonal = list(order = c(1,0,1), period = 7))


acf(narima212$residuals)
acf(narima202$residuals)
acf(narima513$residuals)
acf(narima503$residuals)

narima212$aic
narima202$aic
narima503$aic
narima513$aic
```

```{r}
nsarima212 = arima(Metro.ts1, order = c(2,1,2))
nsarima202 = arima(Metro.ts1, order = c(2,0,2))
nsarima503 = arima(Metro.ts1, order = c(5,0,3))
nsarima513 = arima(Metro.ts1, order = c(5,1,3))

acf(nsarima212$residuals)
acf(nsarima202$residuals)
acf(nsarima513$residuals)
acf(nsarima503$residuals)

nsarima212$aic
nsarima202$aic
nsarima503$aic
nsarima513$aic

```


```{r}
m100 = arima(Metro.ts1, order = c(2,0,2), seasonal = list(order = c(1,0,0), period = 7))
m001 = arima(Metro.ts1, order = c(2,0,2), seasonal = list(order = c(0,0,1), period = 7))
m101 = arima(Metro.ts1, order = c(2,0,2), seasonal = list(order = c(1,0,1), period = 7))
m200 = arima(Metro.ts1, order = c(2,0,2), seasonal = list(order = c(2,0,0), period = 7))
m002 = arima(Metro.ts1, order = c(2,0,2), seasonal = list(order = c(0,0,2), period = 7))
m201 = arima(Metro.ts1, order = c(2,0,2), seasonal = list(order = c(2,0,1), period = 7))
m102 = arima(Metro.ts1, order = c(2,0,2), seasonal = list(order = c(1,0,2), period = 7))
m202 = arima(Metro.ts1, order = c(2,0,2), seasonal = list(order = c(2,0,2), period = 7))



m100$aic
m001$aic
m101$aic
m200$aic

```

